### ISSUE TITLE
动态表格增加行问题

### ISSUE THREAD

**Issue by ns920** [jjxliu306/ng-form-elementplus#3]
弹出方式增加行，第一次点增加不能弹出窗口，需要多次点击

**Comment by jjxliu306** [comment]
目前正在改版ng-form-elementplus，一起处理



在 2023-04-20 11:48:23，"MoeAsuka" ***@***.***> 写道：

弹出方式增加行，第一次点增加不能弹出窗口，需要多次点击

**Comment by jjxliu306** [comment]
尝试更新到2.0.0
